name: 'Jest evaluator'
description: 'Jest evaluator action for Tryber projects'
inputs:
  npm-start:
    description: 'Run npm start and waits to url before testing'
    default: false
  wait-for:
    description: 'Url that npm start command waits for'
    default: 'http://localhost:3000'
  pr_author_username:
    description: 'Pull Request author username'
    required: true

outputs:
  result:
    description: 'Jest unit tests JSON results in base64 format.'
    value: ${{steps.evaluator.outputs.result}}

runs:
  using: 'docker'
  image: 'docker://betrybe/jest-evaluator-action:v9.5'
  id: "evaluator"
  args:
    - ${{ inputs.npm-start }}
    - ${{ inputs.wait-for }}
