name: 'Jest evaluator'
description: 'Jest evaluator action for Tryber projects'
inputs:
  npm-start:
    description: 'Run npm start and waits to url before testing'
    default: false
  wait-for:
    description: 'Url that npm start command waits for'
    default: 'http://localhost:3000'
  pr_author_username:
    description: 'Pull Request author username'
    required: true
  version:
    description: 'Evaluator version to use'
    required: true
    default: latest

outputs:
  result:
    description: 'Jest unit tests JSON results in base64 format.'

runs:
  using: 'docker'
  image: 992764703785.dkr.ecr.us-east-2.amazonaws.com/jest-evaluator-action:${{ inputs.version }}
  args:
    - ${{ inputs.npm-start }}
    - ${{ inputs.wait-for }}
