name: Build and push image to Dockerhub
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Versão do avaliador que você deseja fazer o build"
        required: true
        default: "latest"

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.version }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          push: true
          tags: betrybe/jest-evaluator-action:${{ github.event.inputs.version }}
